[tasks.ssh-connect]
description = "Connect to a VM via DHCP lease"
run = "./scripts/ssh-connect.sh"

[tasks.vm-create]
description = "Create a VM"
usage = '''
arg "<name>" help="VM name according to flake.nix"
'''
run = '''
echo "Creating VM: {{ usage.name }}"
sudo microvm -f git+file://{{config_root}} -c ${usage_name}
'''

[tasks.vm-update]
description = "Update a VM"
usage = '''
arg "<name>" help="VM name according to flake.nix"
'''
run = '''
echo "Updating VM: {{ usage.name }}"
sudo microvm -u ${usage_name}
'''

[tasks.vm-start]
description = "Start a VM"
usage = '''
arg "<name>" help="VM name according to flake.nix"
'''
run = '''
echo "Starting VM: {{ usage.name }}"
sudo systemctl start microvm@${usage_name}.service
'''

[tasks.vm-stop]
description = "Stop a VM"
usage = '''
arg "<name>" help="VM name according to flake.nix"
'''
run = '''
echo "Stopping VM: {{ usage.name }}"
sudo systemctl stop microvm@${usage_name}.service
'''

[tasks.vm-delete]
description = "Delete a VM"
usage = '''
  arg "<name>" help="VM name according to flake.nix"
'''
run = '''
echo "Deleting VM: {{ usage.name }}"
mise r vm-stop ${usage_name}
sudo rm -rf /var/lib/microvms/${usage_name}
'''

[tasks.vm-log-follow]
description = "Log follow a VM"
usage = '''
  arg "<name>" help="VM name according to flake.nix"
'''
run = "journalctl -u microvm@${usage_name}.service -f"
